language: node_js
node_js: 12.16.1
script:
  -echo "Deploying!"
  - npm install --production
  - npm run build
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN
after_success:
  -echo "success!"