language: node_js
node_js:
  -"12.16.1"
jobs:
  include:
    - stage: Push-Requests
      if: ( branch = master || branch = staging || branch = dev ) AND type = push
      script:
        - echo "CI/CD Starting for $BRANCH"
        - jq ".homepage = \"$HOST_URL\"" package.json > package_updated.json && mv package_updated.json package.json
        - npm install --production
        - npm run build
        - npm install -g firebase-tools
        - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
        - firebase deploy --only hosting:$FIREBASE_HOSTING_ID --token $FIREBASE_TOKEN
      after_success:
        - echo "Deployed Successfully"