language: node_js
node_js:
  -"12.16.1"
jobs:
  include:
    - stage: Push-Requests
      if: ( branch = master || branch = staging || branch = dev ) AND type = push
      script:
        - echo "CI/CD Starting for $BRANCH"
      after_success:
        - echo "Deployed Successfully"